SELECT NOMBRE FROM TB_PERSONA;

SELECT CURSO.NOMBRE,TB_PERSONA.NOMBRE
FROM TB_ESTUDIANTE,ASISGNACION, CURSO, TB_PERSONA
WHERE TB_ESTUDIANTE.COD_ESTUDIANTE=ASISGNACION.COD_ESTUDIANTE AND
 CURSO.COD_CURSO=ASISGNACION.COD_CURSO;
 
--JOIN EXPLICITO
SELECT C.NOMBRE,P.COD_PERSONA AS "CODIGO DE PERSONA"
FROM TB_ESTUDIANTE E INNER JOIN ASISGNACION A
ON E.COD_ESTUDIANTE=A.COD_ESTUDIANTE
INNER JOIN CURSO C
ON C.COD_CURSO=A.COD_CURSO 
INNER JOIN TB_PERSONA P
ON P.COD_PERSONA=E.COD_PERSONA;

--ORDER BY
SELECT NOMBRE, FECHA_NACIMIENTO
FROM TB_PERSONA ORDER BY TB_PERSONA.NOMBRE;

SELECT NOMBRE, EXTRACT(YEAR FROM FECHA_NACIMIENTO) AS "AÑO DE NACIMIENTO"
FROM TB_PERSONA ORDER BY 2 DESC;
 