CREATE TABLE TB_DIRECCION(
    COD_DIRECCION NUMBER PRIMARY KEY,
    CALLE VARCHAR(30),
    ZONA NUMBER,
    AVENIDA VARCHAR(20)
);

DROP TABLE TB_DIRECCION;

CREATE TABLE TB_DIRECCION(
    COD_DIRECCION NUMBER,
    CALLE VARCHAR(30),
    ZONA NUMBER,
    AVENIDA VARCHAR(20),
    CONSTRAINT PK_DIRECCION
    PRIMARY KEY(COD_DIRECCION)
);

CREATE TABLE TB_PERSONA(
    COD_PERSONA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(30),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE TB_ESTUDIANTE(
    COD_ESTUDIANTE NUMBER PRIMARY KEY,
    COD_PERSONA NUMBER REFERENCES TB_PERSONA(COD_PERSONA)
);

DROP TABLE TB_ESTUDIANTE;

CREATE TABLE TB_ESTUDIANTE(
    COD_ESTUDIANTE NUMBER PRIMARY KEY,
    COD_PERSONA NUMBER,
    CONSTRAINT FK_TB_ESTUDIANTE
    FOREIGN KEY (COD_PERSONA)
    REFERENCES TB_PERSONA(COD_PERSONA)
);

CREATE TABLE CURSO(
    COD_CURSO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(30)
);

CREATE TABLE ASISGNACION(
    COD_ASIGNACION NUMBER PRIMARY KEY,
    COD_ESTUDIANTE NUMBER REFERENCES TB_ESTUDIANTE(COD_ESTUDIANTE),
    COD_CURSO NUMBER REFERENCES CURSO(COD_CURSO),
    FECHA DATE
);

--INSERCCION
INSERT INTO TB_DIRECCION(COD_DIRECCION,CALLE,ZONA,AVENIDA)
VALUES(2,'TRES',7,'4TA');
--CONSULTA
SELECT *FROM TB_DIRECCION;
--ACTUALIZAR
UPDATE TB_DIRECCION SET CALLE ='1' WHERE COD_DIRECCION=2;
--ELIMINAR
DELETE FROM TB_DIRECCION WHERE COD_DIRECCION=2;

--TB PERSONA
INSERT INTO TB_PERSONA(COD_PERSONA,NOMBRE,FECHA_NACIMIENTO)
VALUES(1,'JASSER','15-02-2024');
SELECT *FROM TB_PERSONA;
UPDATE TB_PERSONA SET FECHA_NACIMIENTO='18-06-2003' WHERE COD_PERSONA=1;
DELETE FROM TB_PERSONA WHERE COD_PERSONA=1;

--TB ESTUDIANTE
INSERT INTO TB_ESTUDIANTE(COD_ESTUDIANTE,COD_PERSONA)
VALUES(1,1);
SELECT * FROM TB_ESTUDIANTE;

--TB CURSO
INSERT INTO CURSO(COD_CURSO,NOMBRE)
VALUES(1,'BASE DE DATOS');
SELECT * FROM CURSO;

--TB ASIGNACION
INSERT INTO ASISGNACION(COD_ASIGNACION,COD_ESTUDIANTE,COD_CURSO,FECHA)
VALUES(1,1,1,'20-07-2024');
SELECT * FROM ASISGNACION;