alter session set "_oracle_script"=true;

--DDL
CREATE USER PROYECTO IDENTIFIED BY toor
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON SYSTEM;

-- PRIVILEGIOS DDL
GRANT CREATE SESSION TO PROYECTO;
GRANT CREATE TABLE TO PROYECTO;
GRANT CREATE PROCEDURE TO PROYECTO;
GRANT CREATE TRIGGER TO PROYECTO;

--PRIVILEGIOS DML
GRANT INSERT ANY TABLE TO PROYECTO;
GRANT DELETE ANY TABLE TO PROYECTO;
GRANT UPDATE ANY TABLE TO PROYECTO;
GRANT SELECT ANY TABLE TO PROYECTO;

GRANT CREATE TYPE TO PROYECTO;
GRANT CREATE SEQUENCE TO PROYECTO;
GRANT CREATE VIEW TO PROYECTO;
